// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login', async function() {
    await driver.get("https://al.uat.attributionledger.com/")
    await driver.manage().window().setRect(1920, 1057)
    await driver.findElement(By.css(".jss137:nth-child(1) > .MuiButton-label-560")).click()
    await driver.findElement(By.id("1-email")).click()
    await driver.findElement(By.id("1-email")).sendKeys("asdasd@asdasd.com")
    await driver.findElement(By.name("password")).sendKeys("asdasdasd")
    await driver.findElement(By.css(".auth0-label-submit")).click()
  })
})
